-- ============================================================
-- Inventory & Order Management System - Database Schema
-- Run this in your Supabase SQL Editor (Project > SQL Editor)
-- Safe to re-run: drops existing tables before recreating them
-- ============================================================

-- Drop tables in reverse dependency order to avoid FK conflicts
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS products CASCADE;

-- ========================
-- PRODUCTS TABLE
-- ========================
CREATE TABLE products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  sku           TEXT UNIQUE NOT NULL,
  price         DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
  quantity      INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================
-- CUSTOMERS TABLE
-- ========================
CREATE TABLE customers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name     TEXT NOT NULL,
  email         TEXT UNIQUE NOT NULL,
  phone_number  TEXT NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================
-- ORDERS TABLE
-- ========================
CREATE TABLE orders (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  total_amount  DECIMAL(10, 2) NOT NULL DEFAULT 0.00 CHECK (total_amount >= 0),
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================
-- ORDER ITEMS TABLE
-- ========================
CREATE TABLE order_items (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id      BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity        INTEGER NOT NULL CHECK (quantity > 0),
  price_at_time   DECIMAL(10, 2) NOT NULL CHECK (price_at_time >= 0)
);

-- ========================
-- INDEXES (Performance)
-- ========================
CREATE INDEX IF NOT EXISTS idx_products_sku        ON products(sku);
CREATE INDEX IF NOT EXISTS idx_customers_email     ON customers(email);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id  ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order   ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);
